### ISSUE TITLE
We need to constrain the view extents of the user map to the world

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe-django#79]
When zooming out we should see only one world!

**Comment by timlinux** [comment]
Currently if you zoom out a long way, you see several copies of the earth map side by side. We should limit zoom level to prevent this some how.

**Comment by timlinux** [comment]
See https://www.mapbox.com/mapbox.js/example/v1.0.0/disable-world-wrapping/

**Comment by lucernae** [comment]
world wrapping is now disabled.,
